# Generated by Django 3.1.4 on 2020-12-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='site',
            field=models.TextField(default='https://www.google.com', max_length=500),
        ),
        migrations.AlterField(
            model_name='slider',
            name='photo',
            field=models.ImageField(upload_to='media/Slider/%Y/'),
        ),
    ]
