# Generated by Django 3.1.4 on 2020-12-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_auto_20201231_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('role', models.CharField(max_length=300)),
                ('fb_link', models.CharField(max_length=300)),
                ('insta_link', models.CharField(max_length=300)),
                ('photo', models.ImageField(upload_to='media/team/%Y/%m/%d/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='site',
            field=models.CharField(default='https://www.google.com', max_length=500),
        ),
    ]
