# Generated by Django 3.1.4 on 2021-01-01 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtuber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='media/ytubers/%Y/%m/')),
                ('video_url', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=300)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('crew', models.CharField(max_length=300)),
                ('camera_type', models.CharField(max_length=300)),
                ('subs_count', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=300)),
                ('is_featured', models.CharField(default=False, max_length=255)),
                ('created_date', models.CharField(blank=True, default=datetime.datetime.now, max_length=100)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
    ]
