# Generated by Django 3.1.4 on 2021-01-01 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20210101_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
